plugins {
    id 'com.android.application'
}

android {
    namespace '{{PACKAGE_NAME}}'
    compileSdk 34

    defaultConfig {
        applicationId "{{PACKAGE_NAME}}"
        minSdk 21
        targetSdk 34
        versionCode {{VERSION_CODE}}
        versionName "{{VERSION_NAME}}"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.9.0'
}
